---

- hosts: web
  become: yes
  roles:
    - { role: nginx }
    - { role: journaldClient }
    - { role: rsyslogClient }

- hosts: log 
  become: yes
  roles:
    - { role: ntpd }
    - { role: journaldSrv }
    - { role: rsyslogSrv }
# Servers of EFK stack
- hosts: logweb
  become: yes
  roles:
    - { role: ansible-efk-master }