home = ENV['HOME'] # Используем глобальную переменную $HOME
CONTROLLER = ENV.fetch('CONTROLLER', 'SATA Controller')

MACHINES = {
:lab12 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.1.101',
        :memory => "512",

},
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.network "public_network" , bridge: "wlp4s0", ip: boxconfig[:ip_addr]
        box.vm.provider "virtualbox" do |vb|
          
          vb.name = boxname.to_s
          vb.memory = boxconfig[:memory]
          # AAA
          
            config.vm.provision :ansible do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "playbook.yml"
          end
        end
      end
    end
  end