---
# tasks file for postfix-server


- name: change my hostname
  hostname: 
    name: "server.otus.local"

- name: Install mail client packages
  yum: 
    name: mailx
    state: present
  
- name: Copy basic config for the postfix postfix-server
  template: 
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: 
    - restart postfix