---
- block:
  - name: 'zabbix-agent | install repo'
    yum:
      name: 'https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm'
      state: present


  - name: 'zabbix-agent | install packages'
    yum:
      name: zabbix-agent
      state: present


  - name: 'zabbix-agent | copy config'
    template:
      src: 'zabbix_agentd.conf.j2'
      dest: '/etc/zabbix/zabbix_agentd.conf'
    notify: restart zabbix-agent


  - name: 'start and enable service'
    systemd:
      name: zabbix-agent
      state: started

  tags: zabbix-agent
