# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :authlab => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1024"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

        #   boxconfig[:disks].each do |dname, dconf|
        #       unless File.exist?(dconf[:dfile])
        #         vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
        #       end
        #       vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        # end
          end
     

      case boxname.to_s
      when "authlab"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          #yum install epel-release -y
          #yum install docker vim -y
          #yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo -y
          #yum install docker-ce docker-ce-cli containerd.io -y
          #systemctl start docker
          #usermod -aG docker vagrant
          #curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          #chmod +x /usr/local/bin/docker-compose
          #sudo chmod +x /usr/local/bin/docker-compose
          #sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          #cp /vagrant/id_rsa /home/vagrant/.ssh/
          #chown vagrant:vagrant /home/vagrant/.ssh/id_rsa 
          #chmod 0600 /home/vagrant/.ssh/id_rsa
          #echo "192.168.11.151  web" >> /etc/hosts
          # Create project structure
          #mkdir ~/dockerlab
          SHELL
          config.vm.provision "shell", path: "./provision.sh"
      end

      end
   end
end

