---
- hosts: otuslinux
  remote_user: vagrant
  tasks:
  - name: install  packages
    become: yes
    become_method: sudo
    yum: name={{ item }} state=present
    with_items:
      - vim
      - mdadm
      - smartmontools
      - hdparm
      - gdisk
  
  - name: make raid 10
    become: yes
    become_method: sudo
    shell: "{{ item }}"
    with_items:
    - mdadm --create /dev/md1 --level=10 --raid-devices=4 /dev/sd[bcde] --spare-devices=1 /dev/sdf
    - mkdir /mnt/md1
    - mkfs.ext4 -F /dev/md1
    - mount /dev/md1 /mnt/md1/
    
      
  - name: make GPT
    become: yes
    become_method: sudo
    shell: "{{ item }}"
    with_items:
    - parted --script /dev/sdg mklabel gpt mkpart primary 1MiB 200MiB mkpart primary 200MiB 400MiB mkpart primary 400MiB 600MiB mkpart primary 600MiB 800MiB mkpart primary 800MiB 1000MiB \
    - sleep 2
  
#  - name: Mount md1
#    become: yes
#    become_method: sudo
#    mount: 
#      path: /mnt/md1
#      src: /dev/md1 
#      fstype: ext4
#      opts: noatime 
#      #fstad: /etc/fstab
#      state: mounted    