home = ENV['HOME'] # Используем глобальную переменную $HOME
CONTROLLER = ENV.fetch('CONTROLLER', 'SATA Controller')

MACHINES = {
:otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.1.101',
        :memory => "512",

},
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.network "public_network" , bridge: "wlp4s0", ip: boxconfig[:ip_addr]
        box.vm.provider "virtualbox" do |vb|
          
          vb.name = boxname.to_s
          vb.memory = boxconfig[:memory]
          # Adding a SATA controller that allows 5 hard drives
          vb.customize ['storagectl', :id, '--name',  'SATA Controller', '--add', 'sata',  '--controller', 'IntelAhci', '--portcount', 5]
          unless File.exist? (home + '/VirtualBox VMs/sata1.vdi')		    
            vb.customize ['createhd', '--filename', home + '/VirtualBox VMs/sata1.vdi' , '--size', 1 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', home + '/VirtualBox VMs/sata1.vdi']
          end
          unless File.exist? (home + '/VirtualBox VMs/sata2.vdi')		    
            vb.customize ['createhd', '--filename', home + '/VirtualBox VMs/sata2.vdi' , '--size', 1 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', home + '/VirtualBox VMs/sata2.vdi']
          end
          unless File.exist? (home + '/VirtualBox VMs/sata3.vdi')		    
            vb.customize ['createhd', '--filename', home + '/VirtualBox VMs/sata3.vdi' , '--size', 1 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', home + '/VirtualBox VMs/sata3.vdi']
          end
          unless File.exist? (home + '/VirtualBox VMs/sata4.vdi')		    
            vb.customize ['createhd', '--filename', home + '/VirtualBox VMs/sata4.vdi' , '--size', 1 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 4, '--device', 0, '--type', 'hdd', '--medium', home + '/VirtualBox VMs/sata4.vdi']
          end
          unless File.exist? (home + '/VirtualBox VMs/sata5.vdi')		    
            vb.customize ['createhd', '--filename', home + '/VirtualBox VMs/sata5.vdi' , '--size', 1 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 5, '--device', 0, '--type', 'hdd', '--medium', home + '/VirtualBox VMs/sata5.vdi']
          end
          unless File.exist? (home + '/VirtualBox VMs/sata6.vdi')		    
            vb.customize ['createhd', '--filename', home + '/VirtualBox VMs/sata6.vdi' , '--size', 1 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 6, '--device', 0, '--type', 'hdd', '--medium', home + '/VirtualBox VMs/sata6.vdi']
          end
            config.vm.provision :ansible do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "playbook.yml"
          end
        end
      end
    end
  end