# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  
  :web => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151',
  } ,
  :log => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

        #   boxconfig[:disks].each do |dname, dconf|
        #       unless File.exist?(dconf[:dfile])
        #         vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
        #       end
        #       vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        # end
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
          
      case boxname.to_s
      
      when "web"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCW+VHI6di+7jZZhnYiCUciVO3oCSJ1xkV+8TINsNy1Itek0BUnorH+Mh6wC5eHoFVsid39v5A5ypzYZvJWhjwu4LNBJFroNhPnpmSBoA7Xk9U+slDI1A6pImop3qQbncMbYMdeyK5yoQO9bgJKDoQG7ak99qp24C4koFHGXO9Bejhenkkct2j0iTQreRyv2y3oSeOvsvQcBFuYS3H0FPhTUII8dx+/tjOTYFaxiA+EkWhuyXfhnrUd60BN5+ajqEgtv4CYZm2MBzDWu3Sor142Ms3R/FbwF1MJKd7JHOzJcTARfnpBqBZi+Or+l9+Pdl8yzxbxO0+9yaj7MGP9eyVT" >> /home/vagrant/.ssh/authorized_keys
        echo "192.168.11.150  log" >> /etc/hosts
        SHELL
      when "log"
        config.vm.provision :file do |file|
          file.source = "./deploy_nginx_web/"
          file.destination = "/home/vagrant/roles/"
        end
       

        config.vm.provision :file do |file|
          file.source = "./ansible-rsyslog-master/"
          file.destination = "/home/vagrant/roles/"
        end
        
        config.vm.provision :file do |file|
          file.source = "./playbook-nginx.yml"
          file.destination = "/home/vagrant/playbook-nginx.yml"
        end
        config.vm.provision :file do |file|
          file.source = "./playbook-rsyslog-client.yml"
          file.destination = "/home/vagrant/playbook-rsyslog-client.yml"
        end
        config.vm.provision :file do |file|
          file.source = "./playbook-rsyslog-server.yml"
          file.destination = "/home/vagrant/playbook-rsyslog-server.yml"
        end
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install epel-release -y
          yum install ansible vim -y
          cp /vagrant/id_rsa /home/vagrant/.ssh/
          chown vagrant:vagrant /home/vagrant/.ssh/id_rsa 
          chmod 0600 /home/vagrant/.ssh/id_rsa
          echo "192.168.11.151  web" >> /etc/hosts
          echo "192.168.11.150  log" >> /etc/hosts
          echo -e "[webservers] \n  web ansible_host=web ansible_ssh_private_key_file=/home/vagrant/.ssh/id_rsa \n [logserver] \n  log ansible_host=log ansible_ssh_private_key_file=/home/vagrant/.ssh/id_rsa" > /etc/ansible/hosts
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCW+VHI6di+7jZZhnYiCUciVO3oCSJ1xkV+8TINsNy1Itek0BUnorH+Mh6wC5eHoFVsid39v5A5ypzYZvJWhjwu4LNBJFroNhPnpmSBoA7Xk9U+slDI1A6pImop3qQbncMbYMdeyK5yoQO9bgJKDoQG7ak99qp24C4koFHGXO9Bejhenkkct2j0iTQreRyv2y3oSeOvsvQcBFuYS3H0FPhTUII8dx+/tjOTYFaxiA+EkWhuyXfhnrUd60BN5+ajqEgtv4CYZm2MBzDWu3Sor142Ms3R/FbwF1MJKd7JHOzJcTARfnpBqBZi+Or+l9+Pdl8yzxbxO0+9yaj7MGP9eyVT" >> /home/vagrant/.ssh/authorized_keys
          # Create project structure 
          mkdir ~/ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook playbook-nginx.yml
          ansible-playbook playbook-rsyslog-server.yml
          ansible-playbook playbook-rsyslog-client.yml
          SHELL
          
      
      end

      end
   end
end
