---
- name: Установка postgres11
  hosts: pgmaster, pgslave
  become: yes
  roles:
   - postgres-install
  tags:
   - pginstall

- name: Настройка master
  hosts: pgmaster
  become: yes
  roles:
   - master-setup
  tags:
    - pgsetup

- name: Настройка slave
  hosts: pgslave
  become: yes
  roles:
   - slave-setup
  tags:
    - slavesetup

- name: Настройка barman
  hosts: barman
  become: yes
  roles:
   - barman-install
  tags:
    - barman

