---
- name: Установка postgres11
  hosts: pgmaster, pgslave
  become: yes
  roles:
   - postgres-install

- name: Настройка master
  hosts: pgmaster
  become: yes
  roles:
   - master-setup

- name: Настройка slave
  hosts: pgslave
  become: yes
  roles:
   - slave-setup

- name: Настройка barman
  hosts: barman
  become: yes
  roles:
   - barman-install
  tags:
    - barman

