# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :pgmaster => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.39'
        
        
  },
  :pgslave => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.40'
        
        
  },
  :barman => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.38'
        
        
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          # box.vm.network "forwarded_port", guest: 8080, host: 8080
          # box.vm.network "forwarded_port", guest: 8443, host: 8443
          # box.vm.network "forwarded_port", guest: 8022, host: 8022

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          #box.vm.network "public_network", use_dhcp_assigned_default_route: true
          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "2048"]
          vb.customize ["modifyvm", :id, "--cpus", "4"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

        #   boxconfig[:disks].each do |dname, dconf|
        #       unless File.exist?(dconf[:dfile])
        #         vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
        #       end
        #       vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        # end
          end
     

      case boxname.to_s
      when "pgmaster"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
         
          mkdir ~/pgmasterlab
          # echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCW+VHI6di+7jZZhnYiCUciVO3oCSJ1xkV+8TINsNy1Itek0BUnorH+Mh6wC5eHoFVsid39v5A5ypzYZvJWhjwu4LNBJFroNhPnpmSBoA7Xk9U+slDI1A6pImop3qQbncMbYMdeyK5yoQO9bgJKDoQG7ak99qp24C4koFHGXO9Bejhenkkct2j0iTQreRyv2y3oSeOvsvQcBFuYS3H0FPhTUII8dx+/tjOTYFaxiA+EkWhuyXfhnrUd60BN5+ajqEgtv4CYZm2MBzDWu3Sor142Ms3R/FbwF1MJKd7JHOzJcTARfnpBqBZi+Or+l9+Pdl8yzxbxO0+9yaj7MGP9eyVT" >> /home/vagrant/.ssh/authorized_keys
          # cp /vagrant/id_rsa /home/vagrant/.ssh/
          # chown vagrant:vagrant /home/vagrant/.ssh/id_rsa 
          # chmod 0600 /home/vagrant/.ssh/id_rsa
          SHELL
          
        
        when "barman"
           box.vm.provision "shell", run: "always", inline: <<-SHELL
             
             mkdir ~/barman
            #  echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCW+VHI6di+7jZZhnYiCUciVO3oCSJ1xkV+8TINsNy1Itek0BUnorH+Mh6wC5eHoFVsid39v5A5ypzYZvJWhjwu4LNBJFroNhPnpmSBoA7Xk9U+slDI1A6pImop3qQbncMbYMdeyK5yoQO9bgJKDoQG7ak99qp24C4koFHGXO9Bejhenkkct2j0iTQreRyv2y3oSeOvsvQcBFuYS3H0FPhTUII8dx+/tjOTYFaxiA+EkWhuyXfhnrUd60BN5+ajqEgtv4CYZm2MBzDWu3Sor142Ms3R/FbwF1MJKd7JHOzJcTARfnpBqBZi+Or+l9+Pdl8yzxbxO0+9yaj7MGP9eyVT" >> /home/vagrant/.ssh/authorized_keys
            #   cp /vagrant/id_rsa /home/vagrant/.ssh/
            #   chown vagrant:vagrant /home/vagrant/.ssh/id_rsa 
            #   chmod 0600 /home/vagrant/.ssh/id_rsa
             SHELL
        #config.vm.provision "shell", path: "./provision.sh"
        end

      end
   end
end