---
- name: Остановка PostgreSQL
  systemd:
    name: postgresql-11
    state: stopped

- name: Удаление  pgdata
  file:
    path: /var/lib/pgsql/11/data
    state: absent

- name: Создание пустой директории pgdata
  file:
    path: /var/lib/pgsql/11/data
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Копирование базы с master
  command: pg_basebackup -X stream -h {{ master_ip }} -D /var/lib/pgsql/11/data/ -P -U replication
  become: yes
  become_user: postgres

- name: Копирование recovery.conf на slave
  template:
    src: recovery.conf 
    dest: /var/lib/pgsql/11/data/recovery.conf
    owner: postgres
    group: postgres
    mode: '0600'
  notify: restart postgres

#firewalld doesn't exist on AWS CentOS 7 by default
- name: Make sure firewalld is installed
  yum: name=firewalld state=present



#unless we start firewalld
- name: Enable and start firewalld
  service: name=firewalld state=started enabled=yes
  

- name: Open post for postgresql
  firewalld:
    port: 5432/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld
