Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "testhost" do |test|
    test.vm.box = "centos/7"
    test.vm.hostname = "testhost"
    test.vm.network :private_network, ip: "192.168.0.131"
  end
  
  test.vm.provision "ansible" do |ansible|
    ansible.playbook = "upgrade-few-streams.yml"
    ansible.groups = {
    "test" => ["testhost"],
    }
    end
  
end
