# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :lab8 => {
        :box_name => "ianmiell/centos7_lvm",
        :ip_addr => '192.168.11.106',
		},
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
  	      bash +x /vagrant/provision.sh
	  SHELL
    config.vm.provision :file do |file|
      file.source = "./module_setup.sh"
      file.destination = "/home/vagrant/module_setup.sh"
    end
    config.vm.provision :file do |file|
      file.source = "./test.sh"
      file.destination = "/home/vagrant/test.sh"
    end
	  config.vm.provision "shell", path: "./provision.sh"

      end
  end
end