---
   - name: Enable forwarding
     sysctl:
       name: net.ipv4.ip_forward
       value: 1
       sysctl_set: yes
       state: present
       reload: yes
   
   - sysctl:
       name: net.ipv4.conf.all.forwarding
       value: 1
       sysctl_set: yes
       state: present
       reload: yes
   
   - sysctl:
       name: net.ipv4.conf.all.rp_filter
       value: 0
       sysctl_set: yes
       state: present
       reload: yes