# -*- mode: ruby -*-
# vi: set ft=ruby :


MACHINES = {
    server: {
        :box_name => 'centos/7',
        :ip_addr => '192.168.111.111',
        :memory => '2048',
        :cpu => 2
    }
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", boxconfig[:memory]]
                vb.customize ["modifyvm", :id, "--cpus", boxconfig[:cpu]]
            end
            box.vm.network "public_network", ip: boxconfig[:ip_addr]

            
            box.vm.provision "shell", inline: <<-SHELL
              mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
              sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
              useradd -m mailuser
              echo "12345678" | passwd mailuser --stdin
              systemctl restart sshd
            SHELL
      
            box.vm.provision "ansible" do |ansible|
                ansible.inventory_path = "staging/hosts"
                ansible.playbook = "provision/main.yml"
            end
        end
 
    end
  end