
---
- hosts: lvm
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:

  - name: install  packages
    become: yes
    become_method: sudo
    tags:
         - packages
    yum: 
        name:
          - vim
          - xfsdump
          - lvm2
  
  - name: Restart server
    tags:
         - reboot
    command: /sbin/shutdown -r +3
    async: 0
    poll: 0
    ignore_errors: true

  - name: Reduce xfs
    tags:
         - start reduce
    shell: "{{ item }}"
    with_items:
      #reduce volume to 8GB
    
    - pvcreate /dev/sdb -y
    - vgcreate vg_root /dev/sdb -y
    - lvcreate -n lv_root -l +100%FREE /dev/vg_root -y
    - mkfs.xfs /dev/vg_root/lv_root
    - mount /dev/vg_root/lv_root /mnt
    - xfsdump -J - /dev/VolGroup00/LogVol00 | xfsrestore -J - /mnt
    - for i in /proc/ /sys/ /dev/ /run/ /boot/;do mount --bind $i /mnt/$i; done
    - chroot /mnt/
    - grub2-mkconfig -o /boot/grub2/grub.cfg
    - cd /boot ; for i in `ls initramfs-*img`; do dracut -v $i `echo $i|sed "s/initramfs-//g;s/.img//g"` --force; done
    - sed -i 's|rd.lvm.lv=VolGroup00/LogVol00|rd.lvm.lv=vg_root/lv_root|g' /boot/grub2/grub.cfg
    
    
    
  
  # - name: Reboot
  #   reboot:
  #     reboot_timeout: 3
  

  - name: Wait for the reboot to complete 
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 600
    

  - name: Continue to reduce xfs after reboot 
    shell: "{{ item }}"
    with_items:
    - lvremove /dev/VolGroup00/LogVol00 -y
    - lvcreate -n VolGroup00/LogVol00 -L 8G /dev/VolGroup00 -y
    - mkfs.xfs /dev/VolGroup00/LogVol00 -y
    - mount /dev/VolGroup00/LogVol00 /mnt
    - xfsdump -J - /dev/vg_root/lv_root | xfsrestore -J - /mnt
    - for i in /proc/ /sys/ /dev/ /run/ /boot/; do mount --bind $i /mnt/$i; done
    - chroot /mnt/
    - grub2-mkconfig -o /boot/grub2/grub.cfg
    - cd /boot ; for i in `ls initramfs-*img`; do dracut -v $i `echo $i|sed "s/initramfs-//g;s/.img//g"` --force; done
    #make mirror 
    - pvcreate /dev/sdc /dev/sdd -y
    - vgcreate vg_var /dev/sdc /dev/sdd
    - lvcreate -L 950M -m1 -n lv_var vg_var
    - mkfs.ext4 /dev/vg_var/lv_var
    - mount /dev/vg_var/lv_var /mnt
    - cp -aR /var/* /mnt/
    - mkdir /tmp/oldvar && mv /var/* /tmp/oldvar
    - umount /mnt
    - mount /dev/vg_var/lv_var /var
    - "echo `blkid | grep var: | awk '{print $2}' /var ext4 defaults 0 0 >> /etc/fstab"
    - lvremove /dev/vg_root/lv_root
    - vgremove /dev/vg_root
    - pvremove /dev/sdb
    - lvcreate -n LogVol_Home -L 2G /dev/VolGroup00
    - mkfs.xfs /dev/VolGroup00/LogVol_Home
    - mount /dev/VolGroup00/LogVol_Home /mnt/
    - cp -aR /home/* /mnt/
    -  rm -rf /home/*
    - umount /mnt
    - mount /dev/VolGroup00/LogVol_Home /home/
    - "echo `blkid | grep Home | awk '{print $2}'` /home xfs defaults 0 0 >> /etc/fstab"
    - touch /home/file{1..20}
    - lvcreate -L 100MB -s -n home_snap /dev/VolGroup00/LogVol_Home
    - rm -f /home/file{11..20}
    - umount /home
    - lvconvert --merge /dev/VolGroup00/home_snap
    - mount /home













