---
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: Добваление записей в /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
       {{ master_ip }} {{ master_hostname }}
       {{ slave_ip }}  {{ slave_hostname }}
       {{ barman_ip }}  {{ barman_hostname }}

- name: Установка репозитория Postgres
  yum:
    name: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm
    state: present

- name: Установка Postgres server
  yum:
    name: postgresql11-server
    state: present

- name: Инициализация БД
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  args:
    creates: /var/lib/pgsql/11/data/postgresql.conf

- name: Старт postgres server
  systemd:
    name: postgresql-11
    state: started
    enabled: yes

- name: Установка barman cli
  yum:
    name: barman-cli
    state: present